on:
  push:
    branches:
      - master
      - 'feature/**'
  pull_request:
    branches-ignore:
      - 'feature/**'

env:
  POSTGRES_PASSWORD: postrges
  POSTGRES_USERNAME: postgres
  POSTGRES_DB: postgres
  DB_HOST: localhost

jobs:
  checkout:
    name: Build image
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USERNAME: ${{ env.POSTGRES_USERNAME }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: checkout the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: print variables
        run: >-
          echo "${{ env.POSTGRES_DB }}"
