on:
  push:
    branches:
      - master
      - 'feature/**'
  pull_request:
    branches-ignore:
      - 'feature/**'

jobs:
  checkout:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2


