on:
  push:
    branches:
      - master
      - 'feature/**'
  pull_request:
    branches-ignore:
      - 'feature/**'

jobs:
  checkout:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v3
      - name: list dir
        run: ls -l


